apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-generator-deployment
  namespace: uvasds-services
  labels:
    app: id-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-generator
  template:
    metadata:
      labels:
        app: id-generator
        environment: production
        owner: nem2p
        team: uvasds
    spec:
      containers:
      - name: id-generator-container
        image: ghcr.io/uvarc/id-generator:{{ .Values.version.idGenerator }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
      imagePullSecrets:
      - name: nmagee-ghcr.io-auth
---
apiVersion: v1
kind: Service
metadata:
  name: id-generator-service
  namespace: uvasds-services
spec:
  selector:
    app: id-generator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-expose-headers: "*"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  name: id-generator-tls-nginx-ingress
  namespace: uvasds-services
spec:
  tls:
  - hosts:
    - ids-sds.pods.uvarc.io
  rules:
  - host: ids-sds.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: id-generator-service
            port:
              number: 8080
